# Generated by Django 3.2.9 on 2022-08-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_switch_btn'),
    ]

    operations = [
        migrations.CreateModel(
            name='turfImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generalTurfImages', models.ImageField(blank=True, null=True, upload_to='media/images')),
            ],
        ),
    ]
