# Generated by Django 3.2.9 on 2022-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_turfimages_generalturfimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotChannelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='turfImages',
            new_name='Esp32camImg',
        ),
        migrations.DeleteModel(
            name='btn',
        ),
        migrations.RenameField(
            model_name='esp32camimg',
            old_name='generalTurfImages',
            new_name='UpdatingImg',
        ),
    ]
